"""Update the library's default temperatures from a benchmark calibration run.

    python scripts/update_calibration.py path/to/constants.json

``constants.json`` is written by the benchmark's ``bench.calibrate_report``
(``results/calibration/part-1/constants.json``). This rewrites the generated
block in ``decisions/calibration.py`` for that model and keeps the other
models, so the shipped numbers can't drift from the report that measured them.
"""

from __future__ import annotations

import argparse
import ast
import json
import re
from pathlib import Path

TARGET = Path(__file__).resolve().parent.parent / "decisions" / "calibration.py"
BEGIN = "# --- generated by scripts/update_calibration.py"
END = "# --- end generated"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("constants")
    args = parser.parse_args()
    new = json.loads(Path(args.constants).read_text())

    text = TARGET.read_text()
    start, end = text.index(BEGIN), text.index(END)
    end = text.index("\n", end) + 1
    current = {node.target.id: ast.literal_eval(node.value)
               for node in ast.parse(text[start:end]).body
               if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name)}
    formulas, families = dict(current["FORMULAS"]), dict(current["FAMILY_TEMPERATURES"])
    aliases = dict(current.get("ALIASES", {}))
    # One "# source (model): ..." line per model.
    sources = dict(re.findall(r"^# source \((.+?)\): (.*)$", text[start:end], re.M))
    model = new["model"]
    sources[model] = new["source"]
    if new.get("alias"):
        # The name the run asked for, when the endpoint answered with another.
        aliases[new["alias"]] = model
    formulas[model] = (round(new["formula"][0], 3), round(new["formula"][1], 3))
    families[model] = {f: round(t, 2) for f, t in sorted(new["family"].items())}

    formula_lines = "".join(f'    "{m}": ({a}, {b}),\n' for m, (a, b) in sorted(formulas.items()))
    family_lines = ""
    for m, temps in sorted(families.items()):
        family_lines += f'    "{m}": {{\n'
        family_lines += "".join(f'        "{f}": {t},\n' for f, t in sorted(temps.items()))
        family_lines += "    },\n"
    alias_lines = "".join(f'    "{a}": "{m}",\n' for a, m in sorted(aliases.items()))
    source_lines = "".join(f"# source ({m}): {src}\n" for m, src in sorted(sources.items()))
    block = f"""{BEGIN}; don't edit by hand ---------
{source_lines}
#: Per model, ``log T = a + b * log(options)``, fitted on the benchmark's text
#: datasets with every dataset weighted equally. Harder, fewer-option tasks
#: need more softening. Only measured models are listed; others keep their
#: raw probabilities.
FORMULAS: dict[str, tuple[float, float]] = {{
{formula_lines}}}

#: Per model and task family, one temperature fitted on that family's
#: datasets. Closer to a task's own best value than the formula, if you can
#: say what kind of task it is.
FAMILY_TEMPERATURES: dict[str, dict[str, float]] = {{
{family_lines}}}

#: Other names for a measured model, such as the serving alias.
ALIASES: dict[str, str] = {{
{alias_lines}}}
{END} ------------------------------------------------------------
"""
    TARGET.write_text(text[:start] + block + text[end:])
    print(f"{model}: formula {formulas[model]}, families {families[model]}")


if __name__ == "__main__":
    main()
