"""Calibrated probabilities and conformal prediction sets.

Two tiers, measured in ``privatemode-decisions-benchmark``:

* **No labels.** Raw probabilities from one masked token are overconfident.
  Dividing the log probabilities by a temperature ``T > 1`` fixes most of
  that. :class:`~decisions.SystemOne` applies the benchmark's value by
  default, from the number of options (:data:`FORMULAS`) or, if you name
  the kind of task, from its family (:data:`FAMILY_TEMPERATURES`). It is a
  better starting point, not a guarantee: the best ``T`` varies by task.
* **A few hundred labels.** :func:`calibrate` fits a temperature and a bias
  per option for your task and a conformal cutoff;
  :meth:`Calibration.predict_set` then returns the options that contain the
  right one with the chosen probability, a guarantee that holds on average
  over new inputs drawn like the labelled ones. Label a *random* sample:
  labels collected only from escalated cases are skewed toward hard ones and
  break the guarantee.

A temperature never changes the chosen option, only how sure the answer says
it is. The bias does change answers, which is what makes it gain accuracy:
use :meth:`Calibration.apply`.
"""

from __future__ import annotations

import math
import random
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass, field, replace

from .types import ChoiceAnswer

# --- generated by scripts/update_calibration.py; don't edit by hand ---------
# source (glm-5.3): privatemode-decisions-benchmark, results/calibration/part-3/glm-5.3/constants.json (run 20260926T101622Z)
# source (glm-5.3-flash): privatemode-decisions-benchmark, results/calibration/part-1/constants.json (run 20260925T215302Z)
# source (kimi-k2.6): privatemode-decisions-benchmark, results/calibration/part-3/kimi-k2.6/constants.json (run 20260926T102643Z)

#: Per model, ``log T = a + b * log(options)``, fitted on the benchmark's text
#: datasets with every dataset weighted equally. Harder, fewer-option tasks
#: need more softening. Only measured models are listed; others keep their
#: raw probabilities.
FORMULAS: dict[str, tuple[float, float]] = {
    "glm-5.3": (0.712, -0.008),
    "glm-5.3-flash": (0.962, -0.076),
    "kimi-k2.6": (1.069, -0.095),
}

#: Per model and task family, one temperature fitted on that family's
#: datasets. Closer to a task's own best value than the formula, if you can
#: say what kind of task it is.
FAMILY_TEMPERATURES: dict[str, dict[str, float]] = {
    "glm-5.3": {
        "intent": 1.75,
        "legal": 2.18,
        "moderation": 2.23,
        "nli": 1.54,
        "qa": 0.96,
        "sentiment": 3.09,
        "topic": 2.41,
    },
    "glm-5.3-flash": {
        "intent": 1.76,
        "legal": 2.24,
        "moderation": 2.96,
        "nli": 1.87,
        "qa": 1.76,
        "sentiment": 2.93,
        "topic": 2.6,
    },
    "kimi-k2.6": {
        "intent": 1.93,
        "legal": 2.09,
        "moderation": 2.97,
        "nli": 2.0,
        "qa": 2.04,
        "sentiment": 3.35,
        "topic": 2.61,
    },
}

#: Other names for a measured model, such as the serving alias.
ALIASES: dict[str, str] = {
    "glm-flash-latest": "glm-5.3-flash",
    "glm-latest": "glm-5.3",
    "kimi-latest": "kimi-k2.6",
}
# --- end generated ------------------------------------------------------------

_FLOOR = 1e-300


def default_temperature(model: str, options: int, family: str | None = None) -> float:
    """The benchmark's temperature for ``model``: by task family if one is
    given, else from the number of options; 1 (raw) for unmeasured models."""
    model = ALIASES.get(model, model)
    if family is not None:
        by_family = FAMILY_TEMPERATURES.get(model, {})
        if family not in by_family:
            known = ", ".join(sorted(by_family)) or "none for this model"
            raise ValueError(f"no temperature for task family {family!r} (known: {known})")
        return by_family[family]
    if model not in FORMULAS:
        return 1.0
    a, b = FORMULAS[model]
    return math.exp(a + b * math.log(max(options, 2)))


def _softmax(logits: Mapping[str, float]) -> dict[str, float]:
    top = max(logits.values())
    weights = {k: math.exp(v - top) for k, v in logits.items()}
    total = math.fsum(weights.values())
    return {k: w / total for k, w in weights.items()}


def _check_temperature(temperature: float) -> None:
    if not (temperature > 0 and math.isfinite(temperature)):
        raise ValueError("temperature must be a positive finite number")


def scale(probabilities: Mapping[str, float], temperature: float) -> dict[str, float]:
    """``p ** (1 / T)``, renormalized."""
    _check_temperature(temperature)
    if temperature == 1:
        return dict(probabilities)
    return _softmax({k: math.log(max(p, _FLOOR)) / temperature for k, p in probabilities.items()})


def peakedness(probabilities: Iterable[float]) -> float:
    """1 for all mass on one option, 0 for a uniform spread."""
    values = list(probabilities)
    if len(values) < 2:
        return 1.0
    entropy = math.fsum(-p * math.log(p) for p in values if p > 0)
    return min(1.0, max(0.0, 1.0 - entropy / math.log(len(values))))


def rescale(answer: ChoiceAnswer, temperature: float) -> ChoiceAnswer:
    """The same answer with its probabilities and confidence rescaled.
    Temperatures compose, so ``answer.temperature`` is multiplied."""
    probabilities = scale(answer.probabilities, temperature)
    base = 1.0 if answer.temperature is None else answer.temperature
    return replace(answer, probabilities=probabilities,
                   confidence=peakedness(probabilities.values()),
                   temperature=base * temperature)


def _nll(logs: Sequence[tuple[list[float], int]], temperature: float) -> float:
    total = 0.0
    for row, gold in logs:
        scaled = [v / temperature for v in row]
        top = max(scaled)
        total += top + math.log(math.fsum(math.exp(v - top) for v in scaled)) - scaled[gold]
    return total / len(logs)


#: How strongly :func:`fit_temperature` pulls towards the temperature the
#: answers already have, in pseudo-examples. On the benchmark it improved a
#: fit from 20 labels by an eighth and changed nothing from 100 labels on.
SHRINKAGE = 5.0


def fit_temperature(answers: Sequence[ChoiceAnswer], labels: Sequence[str], *,
                    shrinkage: float = SHRINKAGE) -> float:
    """The temperature minimizing negative log-likelihood on labelled answers,
    relative to the probabilities they already have.

    With few labels the fit is noisy, so ``shrinkage / n · (log T)²`` pulls
    it towards 1, keeping the answers as they are (for :class:`SystemOne`'s
    answers, the benchmark's default). NLL has a single minimum in ``T`` and
    the pull is convex, so a golden-section search on ``log T`` over
    [0.05, 50] finds the minimum.
    """
    logs = []
    for answer, label in zip(answers, labels, strict=True):
        names = list(answer.probabilities)
        if label not in answer.probabilities:
            raise ValueError(f"label {label!r} is not one of the options {names}")
        logs.append(([math.log(max(answer.probabilities[n], _FLOOR)) for n in names],
                     names.index(label)))
    if not logs:
        raise ValueError("no labelled answers to fit on")
    def loss(log_t: float) -> float:
        return _nll(logs, math.exp(log_t)) + shrinkage / len(logs) * log_t ** 2

    a, b = math.log(0.05), math.log(50.0)
    g = (math.sqrt(5) - 1) / 2
    c, d = b - g * (b - a), a + g * (b - a)
    fc, fd = loss(c), loss(d)
    for _ in range(60):
        if fc < fd:
            b, d, fd = d, c, fc
            c = b - g * (b - a)
            fc = loss(c)
        else:
            a, c, fc = c, d, fd
            d = a + g * (b - a)
            fd = loss(d)
    return math.exp((a + b) / 2)


#: How strongly :func:`fit_temperature_bias` pulls the bias per option
#: towards 0, in pseudo-examples. Chosen on the benchmark: 2 gained 2.0
#: points of accuracy from 100 labels, 0.5 a little more with a worse
#: worst case, 20 less than half.
BIAS_STRENGTH = 2.0


def _labelled_logs(answers: Sequence[ChoiceAnswer], labels: Sequence[str]
                   ) -> tuple[list[str], list[list[float]], list[int]]:
    names = list(answers[0].probabilities) if answers else []
    rows, gold = [], []
    for answer, label in zip(answers, labels, strict=True):
        if list(answer.probabilities) != names:
            raise ValueError("every answer must have the same options, in the same order")
        if label not in answer.probabilities:
            raise ValueError(f"label {label!r} is not one of the options {names}")
        rows.append([math.log(max(answer.probabilities[n], _FLOOR)) for n in names])
        gold.append(names.index(label))
    if not rows:
        raise ValueError("no labelled answers to fit on")
    return names, rows, gold


def _loss_and_gradient(theta: list[float], rows: list[list[float]], gold: list[int],
                       rho: float, lam: float) -> tuple[float, list[float]]:
    """Mean NLL of ``softmax(log p · e^−s + b)`` plus the pulls, and its
    gradient in ``(s, b)``, where ``s = log T``."""
    k = len(theta) - 1
    inverse = math.exp(-theta[0])
    bias = theta[1:]
    total, grad_s = 0.0, 0.0
    grad_b = [0.0] * k
    for row, g in zip(rows, gold):
        z = [v * inverse + b for v, b in zip(row, bias)]
        top = max(z)
        weights = [math.exp(v - top) for v in z]
        norm = math.fsum(weights)
        total += top + math.log(norm) - z[g]
        expected = 0.0
        for j, w in enumerate(weights):
            p = w / norm
            grad_b[j] += p
            expected += p * row[j]
        grad_b[g] -= 1.0
        # d z / d s = −log p · e^−s
        grad_s -= (expected - row[g]) * inverse
    n = len(rows)
    loss = total / n + rho * theta[0] ** 2 + lam * math.fsum(b * b for b in bias)
    gradient = [grad_s / n + 2 * rho * theta[0]] + [v / n + 2 * lam * b for v, b in zip(grad_b, bias)]
    return loss, gradient


def _minimize(function, theta: list[float], iterations: int = 500, memory: int = 10,
              tolerance: float = 1e-8) -> list[float]:
    """L-BFGS with a backtracking line search: needs only gradients, which
    matters without numpy when there are a hundred options or more. Stops
    when the gradient is below ``tolerance`` or the loss stops falling."""
    value, gradient = function(theta)
    steps: list[tuple[list[float], list[float], float]] = []
    stalled = 0
    for _ in range(iterations):
        if max(abs(g) for g in gradient) < tolerance:
            break
        # Two-loop recursion for the search direction.
        q = list(gradient)
        alphas = []
        for s_, y_, rho_ in reversed(steps):
            alpha = rho_ * math.fsum(a * b for a, b in zip(s_, q))
            alphas.append(alpha)
            q = [a - alpha * b for a, b in zip(q, y_)]
        if steps:
            s_, y_, _ = steps[-1]
            q = [v * math.fsum(a * b for a, b in zip(s_, y_)) / math.fsum(b * b for b in y_) for v in q]
        for (s_, y_, rho_), alpha in zip(steps, reversed(alphas)):
            beta = rho_ * math.fsum(a * b for a, b in zip(y_, q))
            q = [v + (alpha - beta) * a for v, a in zip(q, s_)]
        direction = [-v for v in q]
        slope = math.fsum(a * b for a, b in zip(gradient, direction))
        if slope >= 0:      # not a descent direction: restart from the gradient
            steps.clear()
            direction = [-g for g in gradient]
            slope = -math.fsum(g * g for g in gradient)
        size = 1.0
        while True:
            candidate = [t + size * d for t, d in zip(theta, direction)]
            new_value, new_gradient = function(candidate)
            if new_value <= value + 1e-4 * size * slope or size < 1e-12:
                break
            size /= 2
        if size < 1e-12:
            break
        # Rounding keeps the gradient from reaching 0 exactly; stop once the
        # loss no longer moves.
        stalled = stalled + 1 if value - new_value <= 1e-14 * max(1.0, abs(value)) else 0
        if stalled >= 3:
            theta = candidate
            break
        s_ = [a - b for a, b in zip(candidate, theta)]
        y_ = [a - b for a, b in zip(new_gradient, gradient)]
        curvature = math.fsum(a * b for a, b in zip(s_, y_))
        if curvature > 1e-18:
            steps.append((s_, y_, 1 / curvature))
            steps = steps[-memory:]
        theta, value, gradient = candidate, new_value, new_gradient
    return theta


def fit_temperature_bias(answers: Sequence[ChoiceAnswer], labels: Sequence[str], *,
                         shrinkage: float = SHRINKAGE, strength: float = BIAS_STRENGTH,
                         ) -> tuple[float, dict[str, float]]:
    """A temperature and a bias per option, ``softmax(log p / T + b)``,
    minimizing negative log-likelihood on labelled answers.

    The bias corrects a model that favours some options regardless of the
    input; unlike the temperature, it can change the chosen option. On the
    benchmark it gained 2.0 points of accuracy from 100 labels (1.0 from 20,
    3.0 from 500), most where the model over-predicts a class. With two
    options this is Platt scaling. Both are pulled towards no change:
    ``shrinkage / n · (log T)² + strength / n · |b|²``, so with few labels
    the fit stays close to the answers as they are. Returns the temperature
    and the bias per option, centred on 0.
    """
    names, rows, gold = _labelled_logs(answers, labels)
    n = len(rows)
    start = [math.log(fit_temperature(answers, labels, shrinkage=shrinkage))] + [0.0] * len(names)
    theta = _minimize(lambda t: _loss_and_gradient(t, rows, gold, shrinkage / n, strength / n), start)
    centre = math.fsum(theta[1:]) / len(names)
    return math.exp(theta[0]), {name: b - centre for name, b in zip(names, theta[1:])}


def correct(probabilities: Mapping[str, float], temperature: float,
            bias: Mapping[str, float] | None = None) -> dict[str, float]:
    """``softmax(log p / T + b)``: :func:`scale` plus a bias per option."""
    if not bias:
        return scale(probabilities, temperature)
    _check_temperature(temperature)
    return _softmax({k: math.log(max(p, _FLOOR)) / temperature + bias.get(k, 0.0)
                     for k, p in probabilities.items()})


@dataclass(frozen=True)
class Calibration:
    """A task's temperature, bias per option, conformal cutoffs and automation
    threshold, from :func:`calibrate`.

    ``bias`` is added to each option's scaled log probability (empty for a
    temperature alone); it can change the chosen option, so use the answer
    :meth:`apply` returns. ``cutoffs`` apply to ``1 - p`` after the
    correction: an option is in the prediction set when its probability is
    at least ``1 - cutoff``. There is one cutoff for all options, or one per
    option with ``per_class=True``. ``threshold`` is the confidence above
    which :meth:`automate` says yes, ``inf`` if nothing could be certified or
    no ``max_error`` was asked for. ``always_included`` lists the options
    that had too few labels for a cutoff of their own (``per_class=True``):
    they are in every set.

    A calibration is relative to the answers it was fitted on: ``options``
    are their option names in order, and ``base_temperature`` the
    temperature they already had (``ChoiceAnswer.temperature``; for
    :class:`~decisions.SystemOne` answers the model's default, which depends
    on the model and the number of options). Applying it to an answer with
    other options, or at another temperature (a regenerated default, a moved
    alias, another ``temperature=``), raises ``ValueError``: refit instead.
    """

    temperature: float
    cutoffs: Mapping[str, float]
    coverage: float
    examples: int
    threshold: float = math.inf
    max_error: float | None = None
    always_included: tuple[str, ...] = ()
    bias: Mapping[str, float] = field(default_factory=dict)
    options: tuple[str, ...] = ()
    base_temperature: float | None = None

    def __post_init__(self) -> None:
        # Read back from JSON, these arrive as lists.
        object.__setattr__(self, "options", tuple(self.options))
        object.__setattr__(self, "always_included", tuple(self.always_included))

    def check(self, answer: ChoiceAnswer) -> None:
        """Raise ``ValueError`` if the answer isn't like the ones this
        calibration was fitted on (options, or the temperature it has)."""
        if self.options and tuple(answer.probabilities) != self.options:
            raise ValueError(f"calibrated for the options {list(self.options)}, "
                             f"but the answer has {list(answer.probabilities)}")
        if (self.base_temperature is not None and answer.temperature is not None
                and not math.isclose(answer.temperature, self.base_temperature, rel_tol=1e-9)):
            raise ValueError(
                f"calibrated on answers at temperature {self.base_temperature:.4g}, but this "
                f"one is at {answer.temperature:.4g}: the model or its default temperature "
                "changed; refit with calibrate()")

    def probabilities(self, answer: ChoiceAnswer) -> dict[str, float]:
        """The answer's probabilities with this task's correction applied."""
        self.check(answer)
        return correct(answer.probabilities, self.temperature, self.bias)

    def apply(self, answer: ChoiceAnswer) -> ChoiceAnswer:
        """The corrected answer. With a bias the chosen option can change."""
        probabilities = self.probabilities(answer)
        base = 1.0 if answer.temperature is None else answer.temperature
        return replace(answer, choice=max(probabilities, key=probabilities.get),
                       probabilities=probabilities,
                       confidence=peakedness(probabilities.values()),
                       temperature=base * self.temperature)

    def predict_set(self, answer: ChoiceAnswer) -> list[str]:
        """The options that contain the right one with probability
        ``coverage``, most likely first. One option means it can be
        automated at that level; several mean a person should choose.

        Never empty: where no option clears its cutoff, the most likely one
        is returned, which only makes the coverage higher."""
        probabilities = self.probabilities(answer)
        ranked = sorted(probabilities, key=probabilities.get, reverse=True)
        default = self.cutoffs.get("*", 1.0)
        chosen = [name for name in ranked
                  if 1 - probabilities[name] <= self.cutoffs.get(name, default)]
        return chosen or ranked[:1]

    def automate(self, answer: ChoiceAnswer) -> bool:
        """Whether to act on the corrected answer (:meth:`apply`) without a
        person: its confidence is above the threshold that keeps the error
        among automated answers at most ``max_error``, with 90% probability
        over the labelled sample."""
        return max(self.probabilities(answer).values()) >= self.threshold


def _binomial_cdf(k: int, n: int, p: float) -> float:
    """P(X <= k) for X ~ Binomial(n, p)."""
    if k >= n:
        return 1.0
    logs = [math.lgamma(n + 1) - math.lgamma(i + 1) - math.lgamma(n - i + 1)
            + i * math.log(p) + (n - i) * math.log1p(-p) for i in range(k + 1)]
    top = max(logs)
    return min(1.0, math.exp(top) * math.fsum(math.exp(v - top) for v in logs))


def _automation_threshold(confidences: Sequence[float], right: Sequence[bool],
                          max_error: float, delta: float, step: float = 0.05) -> float:
    """Learn then Test, fixed sequence over a grid: see :func:`calibrate`."""
    pairs = sorted(zip(confidences, right, strict=True), key=lambda cr: -cr[0])
    conf = [cf for cf, _ in pairs]
    errors, running = [], 0
    for _, ok in pairs:
        running += not ok
        errors.append(running)
    smallest = math.ceil(math.log(delta) / math.log1p(-max_error))
    chosen = math.inf
    levels = round(1 / step)
    for level in range(1, levels + 1):
        n = math.ceil(len(conf) * level / levels)
        while n < len(conf) and conf[n] == conf[n - 1]:
            n += 1   # a threshold can't split a run of equal confidences
        if n < smallest:
            continue
        if _binomial_cdf(errors[n - 1], n, max_error) > delta:
            break
        chosen = conf[n - 1]
    return chosen


def _cutoff(scores: list[float], coverage: float) -> float:
    """The split-conformal quantile, or 1 (always include) with too few scores."""
    scores = sorted(scores)
    rank = math.ceil((len(scores) + 1) * coverage)
    return 1.0 if rank > len(scores) else scores[rank - 1]


#: Folds for the out-of-fold probabilities :func:`calibrate` sets cutoffs and
#: thresholds on when it fits a bias.
FOLDS = 5
#: Fewer labels than this and :func:`calibrate` fits the temperature alone:
#: a bias per option needs every fold's fit to see a few labels.
MIN_BIAS_LABELS = 2 * FOLDS


def fold_order(n: int, seed: int = 0) -> list[int]:
    """The order in which labelled answers are dealt into folds: a seeded
    permutation, so folds don't depend on how the labels were sorted (a
    file grouped by class would otherwise leave a class out of a fit)."""
    order = list(range(n))
    random.Random(seed).shuffle(order)
    return order


def _out_of_fold(answers: Sequence[ChoiceAnswer], labels: Sequence[str],
                 folds: int) -> list[dict[str, float]]:
    """Each labelled answer corrected by a temperature and bias fitted on the
    other folds: consecutive runs of :func:`fold_order`, the first
    ``n % folds`` one longer."""
    n = len(answers)
    order = fold_order(n)
    out: list[dict[str, float] | None] = [None] * n
    start = 0
    for fold in range(folds):
        size = n // folds + (fold < n % folds)
        if not size:
            continue
        held = order[start:start + size]
        rest = order[:start] + order[start + size:]
        t, b = fit_temperature_bias([answers[i] for i in rest], [labels[i] for i in rest])
        for i in held:
            out[i] = correct(answers[i].probabilities, t, b)
        start += size
    return out  # type: ignore[return-value]


def calibrate(answers: Sequence[ChoiceAnswer], labels: Sequence[str], *,
              coverage: float = 0.9, per_class: bool = False,
              max_error: float | None = None, delta: float = 0.1,
              bias: bool = True) -> Calibration:
    """Fit a temperature, a bias per option, conformal cutoffs and an
    automation threshold on labelled answers.

    ``answers`` are what :meth:`~decisions.SystemOne.system_one` returned for
    one question on a random sample of inputs, ``labels`` the right option
    for each. The guarantees need new inputs to come from the same
    distribution as the labelled ones.

    * **The correction.** A temperature makes the probabilities honest
      without changing the answer; the bias per option (``bias=True``, see
      :func:`fit_temperature_bias`) also corrects a model that favours some
      options, and changes answers: on the benchmark, +2.0 points of
      accuracy from 100 labels. Use :meth:`Calibration.apply` to get the
      corrected answer. ``bias=False`` fits the temperature alone, and so does
      a call with fewer than :data:`MIN_BIAS_LABELS` labels.
    * **Prediction sets** contain the right option with probability
      ``coverage``, on average over new inputs. A few hundred labels make
      that reliable: on the benchmark, a 90% target landed between 85% and
      95% with 100 labels and between 87% and 92% with 500 (5th to 95th
      percentile). With ``per_class=True`` it holds for every option
      separately, which matters when one is rare: on the benchmark's
      imbalanced tasks the rare class was covered only 70–76% of the time
      with one cutoff, and 97% with one per class, at the price of larger sets.
      A cutoff per option needs at least ``coverage / (1 - coverage)`` labels
      of that option, 9 at 90%: an option with fewer is put in every set
      (:attr:`Calibration.always_included`), which makes sets larger. With
      100 labels and an 8% class, that is likely; with a hundred options it
      is most of them.
    * **Automation** (``max_error``, e.g. 0.05): :meth:`Calibration.automate`
      says yes above a confidence threshold chosen so that the error among
      automated answers is at most ``max_error`` with probability
      ``1 - delta``. This is Learn then Test: thresholds that automate 5%,
      10%, ... of the labelled answers are tested in order with an exact
      binomial test, stopping at the first that can't be certified. Picking
      the threshold where the *observed* error equals ``max_error`` instead
      broke its promise on about 40% of the benchmark's samples.

    With a bias, the cutoffs and the threshold are set on out-of-fold
    probabilities: each label's answer corrected by a fit on the other
    :data:`FOLDS` folds. Set on the answers the bias was fitted to, they
    trusted it too much, and at 500 labels the error bound broke on 2 of 23
    benchmark datasets; out-of-fold, at most 1.3% of samples were over it
    and 90% sets covered 90.3–91.3%. A temperature alone is one number and
    uses the same labels for everything, which held (at most 1.1% of samples
    over the bound, coverage 89.8–90.6%) and automates a little more.
    """
    if not 0 < coverage < 1:
        raise ValueError("coverage must be between 0 and 1")
    if max_error is not None and not 0 < max_error < 1:
        raise ValueError("max_error must be between 0 and 1")
    labels = list(labels)
    if not answers:
        raise ValueError("no labelled answers to fit on")
    options = tuple(answers[0].probabilities)
    if any(tuple(a.probabilities) != options for a in answers):
        raise ValueError("every answer must have the same options, in the same order")
    temperatures = {a.temperature for a in answers if a.temperature is not None}
    if len(temperatures) > 1:
        raise ValueError(f"the answers are at different temperatures {sorted(temperatures)}; "
                         "calibrate answers from one model and one temperature setting")
    base = next(iter(temperatures), None)
    offsets: dict[str, float] = {}
    # Too few labels to fit a bias and still hold answers out of it.
    if bias and len(answers) >= MIN_BIAS_LABELS:
        temperature, offsets = fit_temperature_bias(answers, labels)
        scaled = _out_of_fold(answers, labels, FOLDS)
    else:
        temperature = fit_temperature(answers, labels)
        scaled = [scale(a.probabilities, temperature) for a in answers]
    always: tuple[str, ...] = ()
    if per_class:
        by_label: dict[str, list[float]] = {}
        for p, label in zip(scaled, labels, strict=True):
            by_label.setdefault(label, []).append(1 - p[label])
        # An option with too few labels can't be certified: always include it.
        cutoffs = {name: _cutoff(by_label.get(name, []), coverage) for name in scaled[0]}
        always = tuple(name for name, cutoff in cutoffs.items() if cutoff >= 1.0)
    else:
        cutoffs = {"*": _cutoff([1 - p[label] for p, label in zip(scaled, labels, strict=True)],
                                coverage)}
    threshold = math.inf
    if max_error is not None:
        threshold = _automation_threshold(
            [max(p.values()) for p in scaled],
            [max(p, key=p.get) == label for p, label in zip(scaled, labels, strict=True)],
            max_error, delta)
    return Calibration(temperature=temperature, cutoffs=cutoffs, coverage=coverage,
                       examples=len(scaled), threshold=threshold, max_error=max_error,
                       always_included=always, bias=offsets,
                       options=options, base_temperature=base)


def evaluate(answers: Sequence[ChoiceAnswer], labels: Sequence[str], *,
             calibration: Calibration | None = None, bins: int = 15) -> dict[str, float]:
    """How well answers match labels: for an audit sample, or to check a
    :class:`Calibration` on labels it wasn't fitted on.

    Returns ``accuracy``, ``confidence`` (mean top probability),
    ``overconfidence`` (the difference) and ``ece``: the gap between
    confidence and accuracy in ``bins`` equal-size groups of answers, sorted
    by confidence, weighted by size. With a ``calibration`` its correction is
    applied first (which can change answers, with a bias), and the result adds ``coverage`` and ``set_size`` of its
    prediction sets, and ``automated`` and ``automated_error`` for
    :meth:`Calibration.automate`.

    ECE has a floor from sampling alone: a perfectly calibrated model shows a
    few points on a few hundred answers.
    """
    if not answers:
        raise ValueError("no answers to evaluate")
    rows = []
    for answer, label in zip(answers, labels, strict=True):
        p = calibration.probabilities(answer) if calibration else answer.probabilities
        best = max(p, key=p.get)
        rows.append((p[best], best == label))
    n = len(rows)
    accuracy = sum(right for _, right in rows) / n
    confidence = math.fsum(conf for conf, _ in rows) / n
    ordered = sorted(rows, key=lambda row: row[0])
    ece, start = 0.0, 0
    for b in range(bins):
        # Group sizes as numpy's array_split: the first n % bins get one more.
        size = n // bins + (b < n % bins)
        group, start = ordered[start:start + size], start + size
        if group:
            ece += abs(math.fsum(cf for cf, _ in group) / len(group)
                       - sum(ok for _, ok in group) / len(group)) * len(group) / n
    out = {"accuracy": accuracy, "confidence": confidence,
           "overconfidence": confidence - accuracy, "ece": ece}
    if calibration is not None:
        sets = [calibration.predict_set(a) for a in answers]
        automated = [(a, label) for a, label in zip(answers, labels, strict=True)
                     if calibration.automate(a)]
        out.update(
            coverage=sum(label in s for s, label in zip(sets, labels, strict=True)) / n,
            set_size=sum(map(len, sets)) / n,
            automated=len(automated) / n,
            automated_error=(sum(calibration.apply(a).choice != label for a, label in automated)
                             / len(automated) if automated else 0.0))
    return out
